name: Build potrace & vtracer for ARM64

net: [conf,push]

permissions:
  contents: write

jobs:
  potrace-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
      - run: |
          curl -L https://sourceforge.net/projects/potrace/files/potrace-1.16.tar.gz | tar -xz -C /home/runner/
      - run: |
          cd /home/runner/potrace-1.16
          ./configure --host=aarch64-linux-gnu
          make -j4
      - uses: actions/upload-artifact@v4
        with:
          name: potrace
          path: /home/runner/potrace-1.16/potrace

  vtracer-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - uses: rust-actions/rust-toolchain@v2
        with:
          toolchain: stable
          targets: aarch64-unknown-linux-gnu
      - run: |
          git clone https://github.com/visioncortex/vtracer.git /home/runner/vtracer
          cd /home/runner/vtracer
          cargo build --release --target aarch64-unknown-linux-gnu
      - run: cp /home/runner/vtracer/target/aarch64-unknown-linux-gnu/release/vtracer /home/runner/vtracer-aarch64
      - uses: actions/upload-artifact@v4
        with:
          name: vtracer-aarch64
          path: /home/runner/vtracer-aarch64